language: java
sudo: required
matrix:
  include:
    - jdk: openjdk11
addons:
  sonarcloud:
    organization: exasol
    token:
      secure: VRhO896lKG/o7NoCeZwW7kExP7REnVk49P3H8napgJSgTRmvB9RqoIJfDFF4N1HJ1Gki1913gLO2Zdc4anYR/yHIoEN4m3XpGcM/rPkkMYVIBtBaA4hXK9SN2RNd6Wx1Cz91xtPVtzQrNi3g1Fc1uyUkmeNERAIISqQwvtfPA63qiYkmjfMIR+Yku7vzold++IMeob69zpIeZl+cZ51Cx1oGUmSZAy7FlWvyFT5DRSqmqteFl1v6wo/c7B+1imRAtYaQb95eOUVMUJJptXJ2gUyTdDvAklqdD2C01bLtQN7f3jn1T4pQj/OfPKBKCIU2bFuQ5bPiTCQh0U1jYmBhbrv2C4i19OWN+bahvdXFSiUhAywQ/akGSKYagNeenkruANbXgxc0ZuAhRfR6pvcLMsjm+X3gZvZ6Wtb70Ofn5ohEXUFDkwX+6ZbHqLvRBDfZPU5OCBYAEItRzO/NzEejyYXa+FweRxdeBFXmatW+arVyt8xsVBklAF6JUtstyAIFhsFEk2ePQ9pJvXwTz8g8bE2YITxQ6dvTYb2os2uznZgrVS277sxAfqkMHSAqr2lHkcQULt1TWtNmJv0MJIS3H9PyLlZJuQjgXsunTXqwqDPagOr6S+VJ9/Jo7x/DhTVCsGuQnDsZwjhgV5sI6hgf/78SFzTeabwdBnm38ON2MRU=
install:
  - travis_retry mvn dependency:resolve
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration
    verify sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,target/site/jacoco-udf/jacoco.xml
cache:
  directories:
    - "$HOME/.m2"
